version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openssh-client
      - tar xzvf package/simple-stack-*.tgz
      - echo "KSMDEBUG1"
      - git --version
      - echo "KSMDEBUG2"

  pre_build:
    commands:
      - make plan

  build:
    commands:
      - make up

  post_build:
    commands:
      - echo "Done"
