version: 0.2

phases:
  install:
    commands:
      - tar xzvf simple-env-*.tgz
  pre_build:
    commands:
      - make plan ENV=testapply
  build:
    commands:
      - make up ENV=testapply
      - make test ENV=testapply
  post_build:
    commands:
      - make destroy ENV=testapply
