version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openssh-client
      - apt-get install -y ruby2.3 ruby2.3-dev liblzma-dev zlib1g-dev
      - update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby2.3 10
      - update-alternatives --install /usr/bin/gem gem /usr/bin/gem2.3 10
      - gem install bundler
      - tar xzvf package/simple-env-*.tgz

  pre_build:
    commands:
      - make plan

  build:
    commands:
      - make up
      - make test

  post_build:
    commands:
      - make destroy
