---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"
  estate: "%{hiera('estate')}"
  service: "%{hiera('service')}"
  base_dns_domain: "%{hiera('domain_name')}"

  webserver_ssh_public_key_path: "../ssh_keys/webserver_ssh_key.pub"
  bastion_ssh_public_key_path: "../ssh_keys/bastion_ssh_key.pub"
  allowed_cidr: "%{hiera('my_ip')}/32"

ssh_keys:
  - webserver_ssh_key
  - bastion_ssh_key

state:
  # type: local
  type: s3
  scope: deployment
