---
:backends:
  - "overrides"
  - "env"
  - "yaml"
:logger: "noop"
:yaml:
  :datadir: "."
:hierarchy:
  - "deployment/%{deployment}/stack"
  - "delivery/%{delivery}/stack"
  - "delivery-%{delivery}/stack"
  - "account/%{account}/stack"
  - "component-local"
  - "component"
